---
- name: Uninstall web server
  hosts: web
  become: true
  tasks:
    - name: Stop and disable nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Uninstall nginx
      ansible.builtin.package:
        name: nginx
        state: absent
