---

- name: Kräver lösenord för sudo för deploy         
  hosts: all                                       # Körs på både db och web
  become: true                                     # Kräver sudo/root
  vars_files:
    - vault.yml                                    # Krypterade lösenordet läggs i vault

  tasks:

    - name: Sätt lösenord för deploy-användaren    
      ansible.builtin.user:
        name: deploy                               
        password: "{{ deploy_password_hash }}"     # SHA512-hash från vault
        update_password: always                    # Ser till att lösen är rätt vid varje körning

    - name: Säkerställ sudo-regel med lösenord     # Deploy ska kunna sudo, men med lösenord
      ansible.builtin.copy:
        dest: /etc/sudoers.d/deploy                # Vart sudo regeln sparas
        content: |
          deploy ALL=(ALL) ALL                     # Ingen NOPASSWD → lösenord krävs
        owner: root                                
        group: root                                
        mode: '0440'                               
        validate: '/usr/sbin/visudo -cf %s'        # Kollar att syntexen är rätt

    - name: Ta bort eventuell passwordless sudo    # Extra säkerhet för deploy-användaren
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/deploy                # Samma sudoers-fil
        regexp: 'NOPASSWD'                         # Letar efter passwordless sudo
        state: absent                              # Tar bort raden om den finns
        validate: '/usr/sbin/visudo -cf %s'        # Validerar igen
