---
- hosts: db
  become: true
  vars_files:
    vault.yml
  tasks:
    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package:
         name: 
          - mariadb-server
          - python3-PyMySQL
         state: present

    - name: Restart MariaDB to apply new configuration
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: Create a new database with name 'webappdb'
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create a new database user with name 'webappuser'
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ db_password }}"
        priv: "webappdb.*:ALL"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
